# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b715d8cecd080cea225452bb10a5525040ea3e10fec83948acd3916b238115ae0c2f569001e4e811901c934133737a7a32249423431a0203180d5646429e631

test:
  secret_key_base: 3e5e1b2b185f9d2622a674ec9a632e5eb4b2a10febb275c6d00a5b7372a1adb2b48f6e76dcf077544abfb699aea9726826f1a3dce45f22a2cec7a145e6255a75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
